//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Importacion_Vehiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        public int Id_Articulo { get; set; }
        public int Id_Tipo_Articulo { get; set; }
        public int Id_Estado { get; set; }
        public int Id_Pais { get; set; }
        public Nullable<int> Id_Vehiculo { get; set; }
        public string Descripcion { get; set; }
        public int Parte_Vin { get; set; }
        public double Precio_Venta { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Paises Paises { get; set; }
        public virtual Tipo_Articulo Tipo_Articulo { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
