//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Importacion_Vehiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Embarque
    {
        public int Id_Embarque { get; set; }
        public int Id_Empleado { get; set; }
        public int Id_Modalidad_Embarque { get; set; }
        public int Id_Tipo_Articulo { get; set; }
        public int Id_Proveedor { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime Fecha_Recepcion { get; set; }
        public double Valor_Articulo { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Modalidad_Embarque Modalidad_Embarque { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        public virtual Tipo_Articulo Tipo_Articulo { get; set; }
    }
}
