//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Importacion_Vehiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id_Usuario { get; set; }
        public string Usuario1 { get; set; }
        public string Password { get; set; }
        public int Id_Empleado { get; set; }
        public int Habilitado { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
