//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Importacion_Vehiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculos()
        {
            this.Articulos = new HashSet<Articulos>();
        }
    
        public int Id_Vehiculo { get; set; }
        public int Id_Marca { get; set; }
        public int Id_Clasificacion { get; set; }
        public string Motor_cc { get; set; }
        public string Linea { get; set; }
        public int Anio { get; set; }
        public string Color { get; set; }
        public int Numero_Asientos { get; set; }
        public double Tonelaje { get; set; }
        public double Peso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articulos> Articulos { get; set; }
        public virtual Clasificacion_Vehiculo Clasificacion_Vehiculo { get; set; }
        public virtual Marca Marca { get; set; }
    }
}
